CREATE USER 'testpass'@'%' IDENTIFIED BY 'testpass'; 
GRANT ALL PRIVILEGES ON *.* TO 'testpass'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS scopely;

USE scopely;

CREATE TABLE IF NOT EXISTS players (
    id int NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    name varchar(20) NOT NULL UNIQUE KEY
);